[스택, 큐, 덱] 3월 16일
Altu-Bitu-2/Altu-Bitu_algo pull request #3
Opened 2022-03-15 21:31 UTC by byungyurii

#### 내용 & 질문
> 제출합니다
> 1213 기본 파일은 배열을 이용해 풀었습니다. 1213_2.cpp파일은 map을 이용하였습니다. 
> 1918번은 틀린 과제입니다. 어느 부분에서 틀렸는지.. 도저히 찾을 수 없어 이대로 올립니다. 

#### <기존 제출>
> 1213, 1918, 2108, 2504, 18115

#### <추가 제출>
>

2022-03-16 13:41 UTC, mkwkw requested changes
필수 2문제, 선택 3문제 확인 되었습니다! 전체적으로 잘 풀어주셨어요:) 수고하셨습니다~
1918번은 틀린 문제이므로 p1으로 코멘트 작성하였습니다!
2108번에는 조금 더 좋은 코드를 위한 p2 코멘트를 작성하였습니다!

그리고 전체적으로 주석이 많이 부족합니다. 주석 작성은 본인의 코드 작성 및 이해와 타인이 코드를 보고 이해하는 것에 많은 도움을 주므로 주석을 작성하는 습관을 갖는 것이 좋아요:)

수정하시고 오른쪽 상단의 re-request review 버튼 눌러주세요~

2022-03-16 13:41 UTC, mkwkw commented on 3월 11일 - 스택, 큐, 덱/1918.cpp
> +			}
p1. while의 조건문이 조금 부족해보여요! stack에서 pop연산을 할 때 중요하게 쓰이는 기본적인 조건이 있어요:) 이 조건문은 stack이 비었을 때에도 돌아갈 수 있지 않을까요?

2022-03-16 13:41 UTC, mkwkw commented on 3월 11일 - 스택, 큐, 덱/1918.cpp
> +			while (!op.empty() && (op.top() == '*' && op.top() == '/'))
p1. while의 조건문에 수정이 필요해보여요! 지금 s[i]가 *이거나 /일 때 이 while문이 돌아가는데 while문의 조건 중에는 op.top()이 *이고 /인 것이 들어가있어요!

2022-03-16 13:41 UTC, mkwkw commented on 3월 11일 - 스택, 큐, 덱/2108.cpp
> +	findD(v, n, d);
p2. findA,B,C,D함수가 현재 void형으로 리턴하는 것이 없는 것으로 되어있는데 데이터를 리턴하는 형태로 바꾸는 것이 더 좋을 것 같아요!
이렇게 쓰면 실제로는 a,b,c,d가 지역변수이기는 하지만 findA,B,C,D함수 관점에서 봤을 때에는 전역변수로 사용되는 것처럼 보이기 때문이에요.
그리고 변수명과 함수명은 의미와 역할이 분명하게 드러나게 정하는 것이 좋아요. a,b,c,d말고 의미를 담도록 이름을 지어보는 것은 어떨까요?

2022-03-16 14:19 UTC, byungyurii commented on 3월 11일 - 스택, 큐, 덱/1918.cpp
> +			while (!op.empty() && (op.top() == '*' && op.top() == '/'))
연산자우선순위에서 곱셈 나눗셈 > 덧셈 뺄셈 > 괄호 라고 생각했습니다. 때문에, *나 /이 들어왔을 때 만일 스택에 *나 /이 있다면 먼저 처리되어야하고, +,-,(일때는 처리하지 않기 때문에 while문 조건에 op.top()이 *이거나 /일 때 동안 pop을 시켰는데... 튜터님께서 말씀하시는 while 조건문에 문제가 무엇인지 좀 더 자세하게 설명해주실 수 있을까요..?

2022-03-18 05:33 UTC, mkwkw commented on 3월 11일 - 스택, 큐, 덱/1918.cpp
> +			while (!op.empty() && (op.top() == '*' && op.top() == '/'))
답 늦게 드려서 죄송합니다! 지금 조건에서는 op가 비어있지 않고 op.top()이 '*'이고 '/'이어야 돌아갑니다. op.top()은 값을 하나만 가지기 때문에 '*'도 가지고 '/'도 가질 수는 없습니다! 그렇기 때문에 &&이 아니라 ||로 처리해야합니다!

2022-03-18 05:34 UTC, mkwkw requested changes
1918번에 코멘트 작성하였습니다!

2022-03-22 01:46 UTC, mkwkw approved these changes
스택, 큐, 덱 과제는 기한이 이미 지났습니다. 
정수론 한 문제도 같이 커밋되어있는데 원래는 따로 pr로 올려주셔야합니다. 이번에는 제가 확인하였으니 한 문제 확인된 것으로 처리하겠습니다. 나머지 문제는 추가제출해주세요.

2022-03-22 14:06 UTC, merged